// FORT_KNOX_ITEMS: Descent Into Gaming's sealed product inventory.
// Each item belongs to a game (Magic: The Gathering, One Piece, etc.) and
// a specific set/product line within that game.
//
// Schema: { name, game, set, qty, price, note? }
// - qty: how many units currently in stock
// - price: per-unit market price (leave 0 if unknown)
const FORT_KNOX_ITEMS = [
  { name: 'Universes Beyond: FINAL…', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 1, price: 8400.73 },
  { name: 'Chilling Reign Booster Box…', game: 'Pokemon', set: 'Chilling Reign', qty: 1, price: 3438.51 },
  { name: 'Phantasmal Flames Booste…', game: 'Pokemon', set: 'Phantasmal Flames', qty: 2, price: 2781.41 },
  { name: 'The Lord of the Rings: Tales of…', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 1, price: 6580.57 },
  { name: 'Fusion Strike Elite Trainer B…', game: 'Pokemon', set: 'Fusion Strike', qty: 1, price: 3189.97 },
  { name: 'Marvel Super Heroes -…', game: 'Magic: The Gathering', set: 'Marvel Super Heroes', qty: 2, price: 2740.21 },
  { name: 'Carrying On His Will Booster B…', game: 'One Piece', set: 'Carrying On His Will', qty: 1, price: 6095.19 },
  { name: 'Adventure on Kami\'s Island…', game: 'One Piece', set: 'Adventure on Kami\'…', qty: 1, price: 2806.3 },
  { name: 'Teenage Mutant Ninja Turtles -…', game: 'Magic: The Gathering', set: 'Teenage Mutant Nin…', qty: 1, price: 2446.06 },
  { name: 'Extra Booster: One Piece…', game: 'One Piece', set: 'Extra Booster: One…', qty: 1, price: 3619.64 },
  { name: 'Secrets of Strixhaven -…', game: 'Magic: The Gathering', set: 'Secrets of Strixhaven', qty: 1, price: 2797.79 },
  { name: 'Tarkir: Dragonstorm -…', game: 'Magic: The Gathering', set: 'Tarkir: Dragonstorm', qty: 1, price: 2403.31 },
  { name: 'Avatar: The Last Airbender -…', game: 'Magic: The Gathering', set: 'Avatar: The Last…', qty: 1, price: 2402.31 },
  { name: 'The Time of Battle Booster…', game: 'Riftbound', set: 'The Time of Battle', qty: 1, price: 2309.02 },
  { name: 'Universes Beyond: The…', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 1, price: 2030.03 },
  { name: 'One Piece Tin Pack Set Vol. 2…', game: 'One Piece', set: 'One Piece Promotio…', qty: 1, price: 2370.86 },
  { name: 'Prismatic Evolutions…', game: 'Pokemon', set: 'Prismatic Evolutions', qty: 1, price: 2300.95 },
  { name: 'Prismatic Evolutions Elit…', game: 'Pokemon', set: 'Prismatic Evolutions', qty: 1, price: 1893.83 },
  { name: 'Fusion Strike Pokemon Cent…', game: 'Pokemon', set: 'Fusion Strike', qty: 1, price: 2355.57 },
  { name: 'Marvel\'s Spider- Man - Collecto…', game: 'Magic: The Gathering', set: 'Marvel\'s Spider-Man', qty: 1, price: 2133.93 },
  { name: 'Ascended Heroes Elite…', game: 'Pokemon', set: 'Ascended Heroes', qty: 2, price: 1821.08 },
  { name: 'Lorwyn Eclipsed - Collector…', game: 'Magic: The Gathering', set: 'Lorwyn Eclipsed', qty: 1, price: 2351.47 },
  { name: 'Origins - Booster Displa…', game: 'Riftbound', set: 'Origins', qty: 3, price: 2030.13 },
  { name: 'Universes Beyond: FINAL…', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 7, price: 1780.25 },
  { name: 'Universes Beyond: Fallou…', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 3, price: 1760.06 },
  { name: 'Journey Together…', game: 'Pokemon', set: 'Journey Together', qty: 1, price: 1558.11 },
  { name: 'Spiritforged - Booster Displa…', game: 'Riftbound', set: 'Spiritforged', qty: 1, price: 1178.93 },
  { name: 'Universes Beyond:…', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 1, price: 1719.52 },
  { name: 'Aetherdrift - Collector…', game: 'Magic: The Gathering', set: 'Aetherdrift', qty: 1, price: 1447.86 },
  { name: 'Twilight Masquerade…', game: 'Pokemon', set: 'Twilight Masquerade', qty: 1, price: 1091.65 },
  { name: 'Scarlet & Violet Booster Box…', game: 'Pokemon', set: 'Scarlet & Violet Bas…', qty: 1, price: 1674.8 },
  { name: 'Aether Revolt - Booster Box…', game: 'Magic: The Gathering', set: 'Aether Revolt', qty: 1, price: 1250.0 },
  { name: 'Bloomburrow - Collector…', game: 'Magic: The Gathering', set: 'Bloomburrow', qty: 1, price: 1069.11 },
  { name: 'Black Bolt Elite Trainer Box Case', game: 'Pokemon', set: 'Black Bolt', qty: 1, price: 1589.41 },
  { name: 'Prismatic Evolutions…', game: 'Pokemon', set: 'Prismatic Evolutions', qty: 2, price: 1193.43 },
  { name: 'Perfect Order Booster Box…', game: 'Riftbound', set: 'Perfect Order', qty: 1, price: 1031.0 },
  { name: 'The Lost Caverns of…', game: 'Magic: The Gathering', set: 'The Lost Caverns of…', qty: 1, price: 1002.68 },
  { name: 'Phyrexia: All Will Be One -…', game: 'Magic: The Gathering', set: 'Phyrexia: All Will Be…', qty: 1, price: 951.79 },
  { name: 'Wilds of Eldraine -…', game: 'Magic: The Gathering', set: 'Wilds of Eldraine', qty: 1, price: 905.95 },
  { name: 'Fusion Strike Build & Battle…', game: 'Pokemon', set: 'Fusion Strike', qty: 1, price: 990.44 },
  { name: 'Secrets of Strixhaven -…', game: 'Magic: The Gathering', set: 'Secrets of Strixhaven', qty: 1, price: 948.5 },
  { name: 'Mega Charizard X ex Ultra…', game: 'Pokemon', set: 'Miscellaneous Card…', qty: 1, price: 902.62 },
  { name: 'Ravnica Remastered -…', game: 'Magic: The Gathering', set: 'Ravnica Remastered', qty: 1, price: 974.18 },
  { name: 'Bloomburrow - Play Booster…', game: 'Magic: The Gathering', set: 'Bloomburrow', qty: 2, price: 927.0 },
  { name: 'FINAL FANTASY - Chocobo…', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 1, price: 900.0 },
  { name: 'Premium Poster Collection Case', game: 'Pokemon', set: 'Ascended Heroes', qty: 2, price: 965.21 },
  { name: 'Beta - Booster Box Case', game: 'Magic: The Gathering', set: 'Beta', qty: 2, price: 907.84 },
  { name: 'Disney Lorcana: Wilds Unknow…', game: 'Lorcana', set: 'Wilds Unknown', qty: 4, price: 882.44 },
  { name: 'Unleashed - Booster Displa…', game: 'Riftbound', set: 'Unleashed', qty: 1, price: 856.99 },
  { name: 'Magic: The Gathering…', game: 'Magic: The Gathering', set: 'Foundations', qty: 1, price: 804.27 },
  { name: 'Edge of Eternities -…', game: 'Magic: The Gathering', set: 'Edge of Eternities', qty: 6, price: 713.24 },
  { name: 'Outlaws of Thunder…', game: 'Magic: The Gathering', set: 'Outlaws of Thunder…', qty: 1, price: 847.92 },
  { name: 'The Brothers\' War - Collecto…', game: 'Magic: The Gathering', set: 'The Brothers\' War', qty: 1, price: 742.23 },
  { name: 'Eventide - Fat Pack', game: 'Magic: The Gathering', set: 'Eventide', qty: 1, price: 699.99 },
  { name: 'Disney Lorcana: Attack of the…', game: 'Lorcana', set: 'Attack of the Vine!', qty: 1, price: 823.61 },
  { name: 'Chaos Rising Elite Trainer B…', game: 'Pokemon', set: 'Chaos Rising', qty: 1, price: 730.15 },
  { name: 'Perfect Order Elite Trainer B…', game: 'Riftbound', set: 'Perfect Order', qty: 1, price: 694.86 },
  { name: 'Modern Horizons 3 -…', game: 'Magic: The Gathering', set: 'Modern Horizons 3', qty: 1, price: 813.28 },
  { name: 'Commander Legends -…', game: 'Magic: The Gathering', set: 'Commander Legends', qty: 1, price: 722.61 },
  { name: 'Duskmourn: House of Horr…', game: 'Magic: The Gathering', set: 'Duskmourn: House …', qty: 1, price: 688.02 },
  { name: 'FINAL FANTASY Commander…', game: 'Magic: The Gathering', set: 'Commander: FINAL…', qty: 1, price: 679.44 },
  { name: 'Ikoria: Lair of Behemoths -…', game: 'Magic: The Gathering', set: 'Ikoria: Lair of…', qty: 1, price: 623.98 },
  { name: 'Sword & Shield Charizard Ultr…', game: 'Pokemon', set: 'Lost Origin', qty: 1, price: 593.12 },
  { name: 'Universes Beyond: Docto…', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 1, price: 638.08 },
  { name: '151 Elite Trainer Box', game: 'Pokemon', set: 'SV: 151', qty: 2, price: 616.1 },
  { name: 'Modern Horizons 2 -…', game: 'Magic: The Gathering', set: 'Modern Horizons 2', qty: 1, price: 590.32 },
  { name: 'Strixhaven: School of Mage…', game: 'Magic: The Gathering', set: 'Strixhaven: School o…', qty: 1, price: 629.6 },
  { name: 'Riftbound: League of…', game: 'Riftbound', set: 'Riftbound…', qty: 8, price: 606.05 },
  { name: 'Marvel Super Heroes - Gift…', game: 'Magic: The Gathering', set: 'Marvel Super Heroes', qty: 1, price: 558.93 },
  { name: 'Teenage Mutant Ninja Turtles -…', game: 'Magic: The Gathering', set: 'Teenage Mutant Nin…', qty: 1, price: 629.2 },
  { name: 'Commander Legends: Battl…', game: 'Magic: The Gathering', set: 'Commander Legend…', qty: 1, price: 595.38 },
  { name: 'Pitch Black Build & Battle Box…', game: 'Pokemon', set: 'Pitch Black', qty: 1, price: 540.3 },
  { name: '151 Mini Tin Display', game: 'Pokemon', set: 'SV: 151', qty: 2, price: 538.5 },
  { name: 'Destined Rivals Build & Battle…', game: 'Pokemon', set: 'Destined Rivals', qty: 2, price: 527.63 },
  { name: 'Avatar: The Last Airbender -…', game: 'Magic: The Gathering', set: 'Avatar: The Last…', qty: 1, price: 498.94 },
  { name: 'Universes Beyond:…', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 1, price: 530.81 },
  { name: 'Starter Deck 10: Ultimate Deck:…', game: 'One Piece', set: 'Starter Deck 10:…', qty: 1, price: 524.99 },
  { name: 'One Piece Card Game…', game: 'One Piece', set: 'One Piece Promotio…', qty: 1, price: 497.72 },
  { name: 'Dominaria Remastered -…', game: 'Magic: The Gathering', set: 'Dominaria…', qty: 1, price: 530.47 },
  { name: 'Teenage Mutant Ninja Turtles -…', game: 'Magic: The Gathering', set: 'Teenage Mutant Nin…', qty: 1, price: 520.87 },
  { name: 'One Piece Card Game…', game: 'One Piece', set: 'One Piece Promotio…', qty: 1, price: 490.24 },
  { name: 'Kamigawa: Neon Dynasty -…', game: 'Magic: The Gathering', set: 'Kamigawa: Neon…', qty: 1, price: 528.41 },
  { name: 'Commander Masters -…', game: 'Magic: The Gathering', set: 'Commander Masters', qty: 1, price: 506.55 },
  { name: 'Tarkir: Dragonstorm -…', game: 'Magic: The Gathering', set: 'Tarkir: Dragonstorm', qty: 1, price: 486.94 },
  { name: 'Secrets of Strixhaven -…', game: 'Magic: The Gathering', set: 'Secrets of Strixhaven', qty: 1, price: 486.2 },
  { name: 'First Partner Illustration…', game: 'Pokemon', set: 'First Partner…', qty: 11, price: 460.84 },
  { name: 'Innistrad Remastered -…', game: 'Magic: The Gathering', set: 'Innistrad Remastered', qty: 1, price: 448.71 },
  { name: 'Silver Tempest Build & Battle…', game: 'Pokemon', set: 'Silver Tempest', qty: 1, price: 483.17 },
  { name: 'Core Set 2021 - Collector…', game: 'Magic: The Gathering', set: 'Core Set 2021', qty: 1, price: 457.08 },
  { name: 'Double Masters 2022 - Collect…', game: 'Magic: The Gathering', set: 'Double Masters 2022', qty: 1, price: 437.78 },
  { name: 'Avatar: The Last Airbender -…', game: 'Magic: The Gathering', set: 'Avatar: The Last…', qty: 1, price: 482.48 },
  { name: 'Secret Lair Commander…', game: 'Magic: The Gathering', set: 'Secret Lair Drop…', qty: 2, price: 453.72 },
  { name: 'Teenage Mutant Ninja Turtles -…', game: 'Magic: The Gathering', set: 'Teenage Mutant Nin…', qty: 1, price: 436.91 },
  { name: 'Phantasmal Flames Build &…', game: 'Pokemon', set: 'Phantasmal Flames', qty: 1, price: 470.94 },
  { name: 'Marvel Super Heroes -…', game: 'Magic: The Gathering', set: 'Marvel Super Heroes', qty: 2, price: 452.28 },
  { name: 'Zendikar Rising - Collector…', game: 'Magic: The Gathering', set: 'Zendikar Rising', qty: 1, price: 435.99 },
  { name: 'Ascended Heroes First…', game: 'Pokemon', set: 'Ascended Heroes', qty: 2, price: 433.38 },
  { name: 'Marvel Super Heroes -…', game: 'Magic: The Gathering', set: 'Marvel Super Heroes', qty: 5, price: 398.94 },
  { name: 'Team Rocket’s Moltres ex…', game: 'Pokemon', set: 'Miscellaneous Card…', qty: 1, price: 363.99 },
  { name: 'Outlaws of Thunder…', game: 'Magic: The Gathering', set: 'Outlaws of Thunder…', qty: 1, price: 429.6 },
  { name: 'Marvel\'s Spider- Man - Collecto…', game: 'Magic: The Gathering', set: 'Marvel\'s Spider-Man', qty: 1, price: 395.49 },
  { name: 'Unfinity - Collector…', game: 'Magic: The Gathering', set: 'Unfinity', qty: 1, price: 360.28 },
  { name: 'Throne of Eldraine -…', game: 'Magic: The Gathering', set: 'Throne of Eldraine', qty: 1, price: 407.56 },
  { name: 'Adventures in the Forgotten…', game: 'Magic: The Gathering', set: 'Adventures in the…', qty: 1, price: 379.61 },
  { name: 'Secret Lair Drop: Festival in a Bo…', game: 'Magic: The Gathering', set: 'Secret Lair Drop…', qty: 2, price: 354.85 },
  { name: 'Spark of Rebellion - Tw…', game: 'Star Wars: Unlimited', set: 'Spark of Rebellion', qty: 1, price: 400.0 },
  { name: 'Murders at Karlov Manor -…', game: 'Magic: The Gathering', set: 'Murders at Karlov…', qty: 1, price: 377.98 },
  { name: 'Teenage Mutant Ninja Turtles -…', game: 'Magic: The Gathering', set: 'Teenage Mutant Nin…', qty: 1, price: 354.53 },
  { name: 'Dominaria United -…', game: 'Magic: The Gathering', set: 'Dominaria United', qty: 1, price: 349.95 },
  { name: 'Ascended Heroes Mini Ti…', game: 'Pokemon', set: 'Ascended Heroes', qty: 1, price: 327.3 },
  { name: 'Perfect Order Build & Battle…', game: 'Riftbound', set: 'Perfect Order', qty: 1, price: 314.54 },
  { name: 'Theros Beyond Death -…', game: 'Magic: The Gathering', set: 'Theros Beyond Death', qty: 1, price: 347.3 },
  { name: 'Secret Lair Drop: Festival in a Bo…', game: 'Magic: The Gathering', set: 'Secret Lair Drop…', qty: 3, price: 325.42 },
  { name: 'Phantasmal Flames…', game: 'Pokemon', set: 'Phantasmal Flames', qty: 1, price: 313.14 },
  { name: 'Kaldheim - Collector…', game: 'Magic: The Gathering', set: 'Kaldheim', qty: 1, price: 335.37 },
  { name: 'The Lord of the Rings: Tales of…', game: 'Magic: The Gathering', set: 'Commander: The…', qty: 30, price: 319.35 },
  { name: 'Aetherdrift - Collector…', game: 'Magic: The Gathering', set: 'Aetherdrift', qty: 1, price: 303.11 },
  { name: 'Blooming Waters…', game: 'Pokemon', set: 'Miscellaneous Card…', qty: 1, price: 327.57 },
  { name: 'Kanto Power Mini Tin Display', game: 'Pokemon', set: 'Miscellaneous Card…', qty: 1, price: 315.49 },
  { name: 'Celebrations Prime Collection', game: 'Pokemon', set: 'Celebrations', qty: 1, price: 299.92 },
  { name: 'Origins - Booster Display', game: 'Riftbound', set: 'Origins', qty: 3, price: 294.92 },
  { name: 'Streets of New Capenna -…', game: 'Magic: The Gathering', set: 'Streets of New…', qty: 1, price: 274.96 },
  { name: 'Innistrad: Midnight Hunt …', game: 'Magic: The Gathering', set: 'Innistrad: Midnight…', qty: 1, price: 252.9 },
  { name: 'Black Bolt Pokemon Cent…', game: 'Pokemon', set: 'Black Bolt', qty: 1, price: 293.61 },
  { name: 'Journey Together Build …', game: 'Pokemon', set: 'Journey Together', qty: 2, price: 270.01 },
  { name: 'March of the Machine: The…', game: 'Magic: The Gathering', set: 'March of the…', qty: 1, price: 246.06 },
  { name: 'Innistrad: Crimson Vow -…', game: 'Magic: The Gathering', set: 'Innistrad: Crimson…', qty: 1, price: 286.57 },
  { name: 'The Lost Caverns of… (Commander)', game: 'Magic: The Gathering', set: 'Commander: The Lo…', qty: 1, price: 257.34 },
  { name: 'Secret Lair Deck: Dandan Deck', game: 'Magic: The Gathering', set: 'Secret Lair Drop…', qty: 7, price: 243.5 },
  { name: 'Spiritforged - Pre-Rift Event…', game: 'Riftbound', set: 'Spiritforged', qty: 16, price: 275.37 },
  { name: 'Prismatic Evolutions Min…', game: 'Pokemon', set: 'Prismatic Evolutions', qty: 1, price: 253.38 },
  { name: 'Double Pack Set Vol. 10 Display', game: 'One Piece', set: 'Adventure on Kami\'…', qty: 1, price: 240.68 },
  { name: 'FINAL FANTASY - Scene Box Case', game: 'Magic: The Gathering', set: 'Universes Beyond:…', qty: 1, price: 228.16 },
  { name: 'Spiritforged - Booster Display', game: 'Riftbound', set: 'Spiritforged', qty: 1, price: 193.63 },
  { name: '151 Booster Bundle', game: 'Pokemon', set: 'SV: 151', qty: 5, price: 182.87 },
  { name: 'Bloomburrow Commander…', game: 'Magic: The Gathering', set: 'Commander:…', qty: 2, price: 227.31 },
  { name: 'Jump to Lightspeed…', game: 'Star Wars: Unlimited', set: 'Jump to Lightspeed', qty: 1, price: 188.03 },
  { name: 'Unova Heavy Hitters Premiu…', game: 'Pokemon', set: 'Black Bolt', qty: 1, price: 177.63 },
  { name: 'Starter Deck 29: Egghead Display', game: 'One Piece', set: 'Starter Deck 29:…', qty: 1, price: 225.15 },
  { name: 'Teenage Mutant Ninja Turtles…', game: 'Magic: The Gathering', set: 'Commander: Teenag…', qty: 1, price: 186.27 },
  { name: 'Legends of the Force Carbonit…', game: 'Star Wars: Unlimited', set: 'Legends of the Force', qty: 1, price: 176.79 },
  { name: 'First Partner Illustration…', game: 'Pokemon', set: 'First Partner…', qty: 6, price: 207.53 },
  { name: 'Secrets of Strixhaven…', game: 'Magic: The Gathering', set: 'Commander: Secret…', qty: 3, price: 184.99 },
  { name: 'Ascended Heroes Elite…', game: 'Pokemon', set: 'Ascended Heroes', qty: 5, price: 175.43 },
  { name: 'Secrets of Strixhaven -…', game: 'Magic: The Gathering', set: 'Secrets of Strixhaven', qty: 3, price: 167.95 },
  { name: 'Lorwyn Eclipsed Commander…', game: 'Magic: The Gathering', set: 'Commander: Lorwy…', qty: 12, price: 116.44 },
  { name: 'Fusion Strike 3 Pack Blister…', game: 'Pokemon', set: 'Fusion Strike', qty: 12, price: 76.35 },
  { name: 'Paldean Fates Booster Bundle', game: 'Pokemon', set: 'Paldean Fates', qty: 1, price: 157.19 },
  { name: 'Rarity Collection 5 Booster Box', game: 'Pokemon', set: 'Rarity Collection 5', qty: 12, price: 113.24 },
  { name: 'Fusion Strike 3 Pack Blister…', game: 'Pokemon', set: 'Fusion Strike', qty: 12, price: 71.91 },
  { name: 'Edge of Eternities…', game: 'Magic: The Gathering', set: 'Commander: Edge o…', qty: 5, price: 127.97 },
  { name: 'Zacian V-Union Special…', game: 'Pokemon', set: 'Evolving Skies', qty: 1, price: 107.62 },
  { name: 'Marvel Super Heroes Scene…', game: 'Magic: The Gathering', set: 'Marvel Super Heroes', qty: 2, price: 71.31 },
  { name: 'Black Bolt Binder & Unov…', game: 'Pokemon', set: 'Black Bolt', qty: 1, price: 119.75 },
  { name: 'White Flare Booster Bundle', game: 'Pokemon', set: 'White Flare', qty: 1, price: 78.37 },
  { name: 'Learn Together Deck Set', game: 'Riftbound', set: 'Learn Together Dec…', qty: 1, price: 66.02 },
  { name: 'Aetherdrift Commander…', game: 'Magic: The Gathering', set: 'Commander:…', qty: 8, price: 62.96 },
  { name: 'Starter Commander…', game: 'Magic: The Gathering', set: 'Starter Commander…', qty: 2, price: 40.39 },
  { name: 'Starter Commander…', game: 'Magic: The Gathering', set: 'Starter Commander…', qty: 2, price: 30.48 },
  { name: 'Origins - Proving Grounds Box Set', game: 'Riftbound', set: 'Origins', qty: 20, price: 62.89 },
  { name: 'Pokemon TCG: Trainer\'s Toolki…', game: 'Pokemon', set: 'Miscellaneous Card…', qty: 6, price: 40.04 },
  { name: 'Teenage Mutant Ninja Turtles -…', game: 'Magic: The Gathering', set: 'Teenage Mutant Nin…', qty: 30, price: 23.58 },
  { name: 'Mega Zygarde ex Premium…', game: 'Pokemon', set: 'Miscellaneous Card…', qty: 6, price: 47.94 },
  { name: 'Starter Commander…', game: 'Magic: The Gathering', set: 'Starter Commander…', qty: 2, price: 35.27 },
  { name: 'Marvel Super Heroes -…', game: 'Magic: The Gathering', set: 'Marvel Super Heroes', qty: 1, price: 23.0 },
  { name: 'Avatar: The Last Airbender -…', game: 'Magic: The Gathering', set: 'Avatar: The Last…', qty: 4, price: 47.87 },
  { name: 'First Partner Illustration…', game: 'Pokemon', set: 'First Partner…', qty: 12, price: 34.9 },
  { name: 'Starter Commander…', game: 'Magic: The Gathering', set: 'Starter Commander…', qty: 2, price: 20.98 },
  { name: 'Starter Commander…', game: 'Magic: The Gathering', set: 'Starter Commander…', qty: 2, price: 20.62 },
  { name: 'Detective Pikachu Specia…', game: 'Pokemon', set: 'Detective Pikachu', qty: 100, price: 20.16 },
  { name: 'Destined Rivals Sleeved Boost…', game: 'Pokemon', set: 'Destined Rivals', qty: 96, price: 11.68 },
];

// Photo lookup, keyed by lowercase/trimmed item name — same convention as
// LORCANA_PERMANENT_PHOTOS / TRACKER_PERMANENT_PHOTOS.
const FORT_KNOX_PHOTOS = {
  'chilling reign booster box…': 'assets/fortknox/pdf_v3_item_001.webp',
  'phantasmal flames booste…': 'assets/fortknox/pdf_v3_item_002.webp',
  'fusion strike elite trainer b…': 'assets/fortknox/pdf_v3_item_004.webp',
  'marvel super heroes -…': 'assets/fortknox/pdf_v3_item_005.webp',
  'adventure on kami\'s island…': 'assets/fortknox/pdf_v3_item_007.webp',
  'teenage mutant ninja turtles -…': 'assets/fortknox/pdf_v3_item_008.webp',
  'secrets of strixhaven -…': 'assets/fortknox/pdf_v3_item_010.webp',
  'tarkir: dragonstorm -…': 'assets/fortknox/pdf_v3_item_011.webp',
  'the time of battle booster…': 'assets/fortknox/pdf_v3_item_013.webp',
  'universes beyond: the…': 'assets/fortknox/pdf_v3_item_014.webp',
  'prismatic evolutions…': 'assets/fortknox/pdf_v3_item_016.webp',
  'prismatic evolutions elit…': 'assets/fortknox/pdf_v3_item_017.webp',
  'marvel\'s spider- man - collecto…': 'assets/fortknox/pdf_v3_item_019.webp',
  'ascended heroes elite…': 'assets/fortknox/pdf_v3_item_020.webp',
  'origins - booster displa…': 'assets/fortknox/pdf_v3_item_022.webp',
  'universes beyond: final…': 'assets/fortknox/pdf_v3_item_023.webp',
  'journey together…': 'assets/fortknox/pdf_v3_item_025.webp',
  'spiritforged - booster displa…': 'assets/fortknox/pdf_v3_item_026.webp',
  'aetherdrift - collector…': 'assets/fortknox/pdf_v3_item_028.webp',
  'twilight masquerade…': 'assets/fortknox/pdf_v3_item_029.webp',
  'aether revolt - booster box…': 'assets/fortknox/pdf_v3_item_031.webp',
  'bloomburrow - collector…': 'assets/fortknox/pdf_v3_item_032.webp',
  'perfect order booster box…': 'assets/fortknox/pdf_v3_item_035.webp',
  'phyrexia: all will be one -…': 'assets/fortknox/pdf_v3_item_037.webp',
  'wilds of eldraine -…': 'assets/fortknox/pdf_v3_item_038.webp',
  'secrets of strixhaven -…': 'assets/fortknox/pdf_v3_item_040.webp',
  'mega charizard x ex ultra…': 'assets/fortknox/pdf_v3_item_041.webp',
  'bloomburrow - play booster…': 'assets/fortknox/pdf_v3_item_043.webp',
  'final fantasy - chocobo…': 'assets/fortknox/pdf_v3_item_044.webp',
  'beta - booster box case': 'assets/fortknox/pdf_v3_item_046.webp',
  'disney lorcana: wilds unknow…': 'assets/fortknox/pdf_v3_item_047.webp',
  'magic: the gathering…': 'assets/fortknox/pdf_v3_item_049.webp',
  'edge of eternities -…': 'assets/fortknox/pdf_v3_item_050.webp',
  'the brothers\' war - collecto…': 'assets/fortknox/pdf_v3_item_052.webp',
  'eventide - fat pack': 'assets/fortknox/pdf_v3_item_053.webp',
  'chaos rising elite trainer b…': 'assets/fortknox/pdf_v3_item_055.webp',
  'perfect order elite trainer b…': 'assets/fortknox/pdf_v3_item_056.webp',
  'commander legends -…': 'assets/fortknox/pdf_v3_item_058.webp',
  'duskmourn: house of horr…': 'assets/fortknox/pdf_v3_item_059.webp',
  'ikoria: lair of behemoths -…': 'assets/fortknox/pdf_v3_item_061.webp',
  'sword & shield charizard ultr…': 'assets/fortknox/pdf_v3_item_062.webp',
  '151 elite trainer box': 'assets/fortknox/pdf_v3_item_064.webp',
  'modern horizons 2 -…': 'assets/fortknox/pdf_v3_item_065.webp',
  'riftbound: league of…': 'assets/fortknox/pdf_v3_item_067.webp',
  'marvel super heroes - gift…': 'assets/fortknox/pdf_v3_item_068.webp',
  'commander legends: battl…': 'assets/fortknox/pdf_v3_item_070.webp',
  'pitch black build & battle box…': 'assets/fortknox/pdf_v3_item_071.webp',
  '151 mini tin display': 'assets/fortknox/pdf_v3_item_072.webp',
  'destined rivals build & battle…': 'assets/fortknox/pdf_v3_item_073.webp',
  'avatar: the last airbender -…': 'assets/fortknox/pdf_v3_item_074.webp',
  'universes beyond:…': 'assets/fortknox/pdf_v3_item_075.webp',
  'starter deck 10: ultimate deck:…': 'assets/fortknox/pdf_v3_item_076.webp',
  'one piece card game…': 'assets/fortknox/pdf_v3_item_077.webp',
  'dominaria remastered -…': 'assets/fortknox/pdf_v3_item_078.webp',
  'teenage mutant ninja turtles -…': 'assets/fortknox/pdf_v3_item_079.webp',
  'one piece card game…': 'assets/fortknox/pdf_v3_item_080.webp',
  'kamigawa: neon dynasty -…': 'assets/fortknox/pdf_v3_item_081.webp',
  'commander masters -…': 'assets/fortknox/pdf_v3_item_082.webp',
  'tarkir: dragonstorm -…': 'assets/fortknox/pdf_v3_item_083.webp',
  'secrets of strixhaven -…': 'assets/fortknox/pdf_v3_item_084.webp',
  'first partner illustration…': 'assets/fortknox/pdf_v3_item_085.webp',
  'innistrad remastered -…': 'assets/fortknox/pdf_v3_item_086.webp',
  'silver tempest build & battle…': 'assets/fortknox/pdf_v3_item_087.webp',
  'core set 2021 - collector…': 'assets/fortknox/pdf_v3_item_088.webp',
  'double masters 2022 - collect…': 'assets/fortknox/pdf_v3_item_089.webp',
  'avatar: the last airbender -…': 'assets/fortknox/pdf_v3_item_090.webp',
  'secret lair commander…': 'assets/fortknox/pdf_v3_item_091.webp',
  'teenage mutant ninja turtles -…': 'assets/fortknox/pdf_v3_item_092.webp',
  'phantasmal flames build &…': 'assets/fortknox/pdf_v3_item_093.webp',
  'marvel super heroes -…': 'assets/fortknox/pdf_v3_item_094.webp',
  'zendikar rising - collector…': 'assets/fortknox/pdf_v3_item_095.webp',
  'ascended heroes first…': 'assets/fortknox/pdf_v3_item_096.webp',
  'marvel super heroes -…': 'assets/fortknox/pdf_v3_item_097.webp',
  'team rocket’s moltres ex…': 'assets/fortknox/pdf_v3_item_098.webp',
  'outlaws of thunder…': 'assets/fortknox/pdf_v3_item_099.webp',
  'marvel\'s spider- man - collecto…': 'assets/fortknox/pdf_v3_item_100.webp',
  'unfinity - collector…': 'assets/fortknox/pdf_v3_item_101.webp',
  'throne of eldraine -…': 'assets/fortknox/pdf_v3_item_102.webp',
  'adventures in the forgotten…': 'assets/fortknox/pdf_v3_item_103.webp',
  'secret lair drop: festival in a bo…': 'assets/fortknox/pdf_v3_item_104.webp',
  'spark of rebellion - tw…': 'assets/fortknox/pdf_v3_item_105.webp',
  'murders at karlov manor -…': 'assets/fortknox/pdf_v3_item_106.webp',
  'teenage mutant ninja turtles -…': 'assets/fortknox/pdf_v3_item_107.webp',
  'ascended heroes mini ti…': 'assets/fortknox/pdf_v3_item_109.webp',
  'perfect order build & battle…': 'assets/fortknox/pdf_v3_item_110.webp',
  'theros beyond death -…': 'assets/fortknox/pdf_v3_item_111.webp',
  'secret lair drop: festival in a bo…': 'assets/fortknox/pdf_v3_item_112.webp',
  'phantasmal flames…': 'assets/fortknox/pdf_v3_item_113.webp',
  'kaldheim - collector…': 'assets/fortknox/pdf_v3_item_114.webp',
  'the lord of the rings: tales of…': 'assets/fortknox/pdf_v3_item_115.webp',
  'aetherdrift - collector…': 'assets/fortknox/pdf_v3_item_116.webp',
  'blooming waters…': 'assets/fortknox/pdf_v3_item_117.webp',
  'kanto power mini tin display': 'assets/fortknox/pdf_v3_item_118.webp',
  'celebrations prime collection': 'assets/fortknox/pdf_v3_item_119.webp',
  'origins - booster display': 'assets/fortknox/pdf_v3_item_120.webp',
  'streets of new capenna -…': 'assets/fortknox/pdf_v3_item_121.webp',
  'innistrad: midnight hunt …': 'assets/fortknox/pdf_v3_item_122.webp',
  'black bolt pokemon cent…': 'assets/fortknox/pdf_v3_item_123.webp',
  'journey together build …': 'assets/fortknox/pdf_v3_item_124.webp',
  'march of the machine: the…': 'assets/fortknox/pdf_v3_item_125.webp',
  'innistrad: crimson vow -…': 'assets/fortknox/pdf_v3_item_126.webp',
  'the lost caverns of… (commander)': 'assets/fortknox/pdf_v3_item_127.webp',
  'secret lair deck: dandan deck': 'assets/fortknox/pdf_v3_item_128.webp',
  'spiritforged - pre-rift event…': 'assets/fortknox/pdf_v3_item_129.webp',
  'prismatic evolutions min…': 'assets/fortknox/pdf_v3_item_130.webp',
  'double pack set vol. 10 display': 'assets/fortknox/pdf_v3_item_131.webp',
  'final fantasy - scene box case': 'assets/fortknox/pdf_v3_item_132.webp',
  'spiritforged - booster display': 'assets/fortknox/pdf_v3_item_133.webp',
  '151 booster bundle': 'assets/fortknox/pdf_v3_item_134.webp',
  'bloomburrow commander…': 'assets/fortknox/pdf_v3_item_135.webp',
  'jump to lightspeed…': 'assets/fortknox/pdf_v3_item_136.webp',
  'unova heavy hitters premiu…': 'assets/fortknox/pdf_v3_item_137.webp',
  'starter deck 29: egghead display': 'assets/fortknox/pdf_v3_item_138.webp',
  'teenage mutant ninja turtles…': 'assets/fortknox/pdf_v3_item_139.webp',
  'legends of the force carbonit…': 'assets/fortknox/pdf_v3_item_140.webp',
  'first partner illustration…': 'assets/fortknox/pdf_v3_item_141.webp',
  'secrets of strixhaven…': 'assets/fortknox/pdf_v3_item_142.webp',
  'ascended heroes elite…': 'assets/fortknox/pdf_v3_item_143.webp',
  'secrets of strixhaven -…': 'assets/fortknox/pdf_v3_item_144.webp',
  'lorwyn eclipsed commander…': 'assets/fortknox/pdf_v3_item_145.webp',
  'fusion strike 3 pack blister…': 'assets/fortknox/pdf_v3_item_146.webp',
  'paldean fates booster bundle': 'assets/fortknox/pdf_v3_item_147.webp',
  'rarity collection 5 booster box': 'assets/fortknox/pdf_v3_item_148.webp',
  'fusion strike 3 pack blister…': 'assets/fortknox/pdf_v3_item_149.webp',
  'edge of eternities…': 'assets/fortknox/pdf_v3_item_150.webp',
  'zacian v-union special…': 'assets/fortknox/pdf_v3_item_151.webp',
  'marvel super heroes scene…': 'assets/fortknox/pdf_v3_item_152.webp',
  'black bolt binder & unov…': 'assets/fortknox/pdf_v3_item_153.webp',
  'white flare booster bundle': 'assets/fortknox/pdf_v3_item_154.webp',
  'learn together deck set': 'assets/fortknox/pdf_v3_item_155.webp',
  'aetherdrift commander…': 'assets/fortknox/pdf_v3_item_156.webp',
  'starter commander…': 'assets/fortknox/pdf_v3_item_157.webp',
  'starter commander…': 'assets/fortknox/pdf_v3_item_158.webp',
  'origins - proving grounds box set': 'assets/fortknox/pdf_v3_item_159.webp',
  'pokemon tcg: trainer\'s toolki…': 'assets/fortknox/pdf_v3_item_160.webp',
  'teenage mutant ninja turtles -…': 'assets/fortknox/pdf_v3_item_161.webp',
  'mega zygarde ex premium…': 'assets/fortknox/pdf_v3_item_162.webp',
  'starter commander…': 'assets/fortknox/pdf_v3_item_163.webp',
  'marvel super heroes -…': 'assets/fortknox/pdf_v3_item_164.webp',
  'avatar: the last airbender -…': 'assets/fortknox/pdf_v3_item_165.webp',
  'first partner illustration…': 'assets/fortknox/pdf_v3_item_166.webp',
  'starter commander…': 'assets/fortknox/pdf_v3_item_167.webp',
  'starter commander…': 'assets/fortknox/pdf_v3_item_168.webp',
  'detective pikachu specia…': 'assets/fortknox/pdf_v3_item_169.webp',
  'destined rivals sleeved boost…': 'assets/fortknox/pdf_v3_item_170.webp',
};

function fortKnoxKeyFor(name) {
  return (name || '').trim().toLowerCase();
}
